require("global-note").setup({
  directory = "~/notes/",

  additional_presets = {
    projects = {
      filename = "to-dos.md",
      title = "TODOS",
      command_name = "TodoNote",
      -- All not specified options are used from the root.
    },

    food = {
      filename = "how.md",
      title = "Hows",
      command_name = "HowNote",
      -- All not specified options are used from the root.
    },

    habits = {
      filename = "habits.md",
      title = "Devs",
      command_name = "DevNote",
      -- All not specified options are used from the root.
    },
  },
})

return {}
-- Functions to toggle notes:
-- require("global-note").toggle_note()
-- require("global-note").toggle_note("projects")
-- require("global-note").toggle_note("food")

-- Commands to toggle notes (they are generated by command_name field):
-- :GlobalNote -- by default
-- :ProjectsNote
-- :FoodNote
